version: '3'

services:
  db:
    image: mysql:5.7.32
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: vigorita
    volumes:
      - dbdata:/var/lib/mysql
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  --default-authentication-plugin=mysql_native_password'
    networks:
      - wp-nginx

  wordpress:
    depends_on:
      - db
    image: wordpress:5.7.2-php7.4-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_USER: root
        WORDPRESS_DB_PASSWORD: root
        WORDPRESS_DB_NAME: vigorita
    volumes:
      - ./:/var/www/html
      - ./wp-content/plugins/:/var/www/html/wp-content/plugins/:rw
      - ./wp-content/themes/:/var/www/html/wp-content/themes/:rw
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wp-nginx

  nginx:
    depends_on:
      - wordpress
    image: nginx:1.19.3-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - wp-nginx


      
volumes:
  dbdata:
  
networks:
  wp-nginx: